# Sequence — iOS habit tracker
# The Xcode project is generated by XcodeGen from project.yml (source of truth);
# *.xcodeproj is gitignored, so we regenerate it as needed.
#
# Common usage:
#   make run      # regenerate, build, install, and launch on the simulator
#   make test     # run the unit test suite
#   make graph    # open the graphify knowledge-graph in your browser
#
# Override the simulator if you don't have an iPhone 17 Pro:
#   make run SIMULATOR="iPhone 16 Pro"

SCHEME      := Sequence
PROJECT     := Sequence.xcodeproj
BUNDLE_ID   := com.sequence.app
SIMULATOR   ?= iPhone 17 Pro
DESTINATION := platform=iOS Simulator,name=$(SIMULATOR)
APP_PATH     = $(shell find ~/Library/Developer/Xcode/DerivedData/Sequence-*/Build/Products/Debug-iphonesimulator -maxdepth 1 -name "Sequence.app" 2>/dev/null | head -1)

.PHONY: all run build test generate boot install launch fresh graph update clean help

all: run ## Default: build and run

generate: ## Regenerate Sequence.xcodeproj from project.yml
	xcodegen generate

build: generate ## Build the app for the simulator
	xcodebuild -project $(PROJECT) -scheme $(SCHEME) -destination '$(DESTINATION)' build

test: generate ## Run the unit test suite
	xcodebuild -project $(PROJECT) -scheme $(SCHEME) -destination '$(DESTINATION)' test

boot: ## Boot the simulator (no-op if already booted) and open Simulator.app
	@xcrun simctl boot "$(SIMULATOR)" 2>/dev/null || true
	@open -a Simulator

install: ## Install the most recent build onto the booted simulator
	@test -n "$(APP_PATH)" || (echo "No build found — run 'make build' first." && exit 1)
	xcrun simctl install booted "$(APP_PATH)"

launch: ## Launch the installed app
	xcrun simctl launch booted $(BUNDLE_ID)

run: build boot install launch ## Build, boot, install, and launch (the one you want)
	@echo "Sequence is running on $(SIMULATOR)."

fresh: build boot ## Clean install: wipe app data (re-show onboarding), then launch
	-xcrun simctl uninstall booted $(BUNDLE_ID)
	xcrun simctl install booted "$(APP_PATH)"
	xcrun simctl launch booted $(BUNDLE_ID)
	@echo "Fresh install launched — onboarding will show."

graph: ## Open the graphify knowledge-graph in the default browser
	@test -f graphify-out/graph.html && open graphify-out/graph.html || echo "No graph yet — run /graphify first."

update: ## Refresh the graphify graph after code changes (AST-only, free)
	@command -v graphify >/dev/null 2>&1 && graphify update . || echo "graphify not installed."

clean: ## Remove generated project and build artifacts
	rm -rf $(PROJECT)
	xcodebuild -project $(PROJECT) -scheme $(SCHEME) clean 2>/dev/null || true

help: ## Show this help
	@grep -E '^[a-zA-Z_-]+:.*?## .*$$' $(MAKEFILE_LIST) | \
		awk 'BEGIN {FS = ":.*?## "}; {printf "  \033[36m%-10s\033[0m %s\n", $$1, $$2}'
